export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CLEAN_PROJECT_STATE = "CLEAN_PROJECT_STATE";
export const PROFILE_DETAILS_START = 'PROFILE_DETAILS_START';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';

export const SAVE_TOKEN_START = 'SAVE_TOKEN_START';
export const SAVE_TOKEN_SUCCESS = 'SAVE_TOKEN_SUCCESS';

export const FIRST_CONFIGURATION_START = 'FIRST_CONFIGURATION_START';
export const FIRST_CONFIGURATION_SUCCESS = 'FIRST_CONFIGURATION_SUCCESS';
export const FIRST_CONFIGURATION_COMPLETED_SUCCESS = 'FIRST_CONFIGURATION_COMPLETED_SUCCESS';
export const FIRST_CONFIGURATION_FAIL = 'FIRST_CONFIGURATION_FAIL';

export const PROJECT_START = 'PROJECT_START';
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_FAIL = 'PROJECT_FAIL';

export const GET_PROJECT_START = 'GET_PROJECT_START';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL';

export const GET_USER_PROJECTS_START = 'GET_USER_PROJECTS_START';
export const GET_USER_PROJECTS_SUCCESS = 'GET_USER_PROJECTS_SUCCESS';
export const GET_USER_PROJECTS_FAIL = 'GET_USER_PROJECTS_FAIL';

export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';

export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL'

export const CLEAN_LEVEL_STATE = ''
export const LEVEL_START = 'LEVEL_START'
export const LEVEL_SUCCESS = 'LEVEL_SUCCESS'
export const LEVEL_FAIL = 'LEVEL_FAIL'

export const GET_LEVELS_START = 'GET_LEVELS_START'
export const GET_LEVELS_SUCCESS = 'GET_LEVELS_SUCCESS'
export const GET_LEVELS_FAIL = 'GET_LEVELS_FAIL'

export const GET_LEVEL_START = 'GET_LEVEL_START'
export const GET_LEVEL_SUCCESS = 'GET_LEVEL_SUCCESS'
export const GET_LEVEL_FAIL = 'GET_LEVEL_FAIL'

export const DELETE_LEVEL_START = 'DELETE_LEVEL_START'
export const DELETE_LEVEL_SUCCESS = 'DELETE_LEVEL_SUCCESS'
export const DELETE_LEVEL_FAIL = 'DELETE_LEVEL_FAIL'

export const UPDATE_LEVEL_START = 'UPDATE_LEVEL_START'
export const UPDATE_LEVEL_SUCCESS = 'UPDATE_LEVEL_SUCCESS'
export const UPDATE_LEVEL_FAIL = 'UPDATE_LEVEL_FAIL'

export const UPDATE_USER_LEVEL_START = 'UPDATE_USER_LEVEL_START'
export const UPDATE_USER_LEVEL_SUCCESS = 'UPDATE_USER_LEVEL_SUCCESS'
export const UPDATE_USER_LEVEL_FAIL = 'UPDATE_USER_LEVEL_FAIL'

export const SYNC_GITLAB_GITHUB_START = 'SYNC_GITLAB_GITHUB_START';
export const SYNC_GITLAB_GITHUB_SUCCESS = 'SYNC_GITLAB_GITHUB_SUCCESS';
export const SYNC_GITLAB_GITHUB_FAIL = 'SYNC_GITLAB_GITHUB_FAIL';

export const USER_GET_DATA_START = 'USER_GET_DATA_START';
export const USER_GET_DATA_SUCCESS = 'USER_GET_DATA_SUCCESS';
export const USER_GET_DATA_FAIL = 'USER_GET_DATA_FAIL';

export const USER_GET_USERNAMES_LIKE_START = 'USER_GET_USERNAMES_LIKE_START';
export const USER_GET_USERNAMES_LIKE_SUCCESS = 'USER_GET_USERNAMES_LIKE_SUCCESS';
export const USER_GET_USERNAMES_LIKE_FAIL = 'USER_GET_USERNAMES_LIKE_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CLEAN_TEAM_STATE = 'CLEAN_TEAM_STATE'
export const SAVE_NEW_TEAM_START = 'SAVE_NEW_TEAM_START';
export const SAVE_NEW_TEAM_SUCCESS = 'SAVE_NEW_TEAM_SUCCESS';
export const SAVE_NEW_TEAM_FAIL = 'SAVE_NEW_TEAM_FAIL';

export const UPDATE_TEAM_START = 'UPDATE_TEAM_START';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAIL = 'UPDATE_TEAM_FAIL';

export const DELETE_TEAM_START = 'DELETE_TEAM_START';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL';

export const GET_TEAMS_START = 'GET_TEAMS_START';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAIL = 'GET_TEAMS_FAIL';

export const GET_TEAM_START = 'GET_TEAM_START';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL';

export const ADD_TEAM_MEMBER_START = 'ADD_TEAM_MEMBER_START';
export const ADD_TEAM_MEMBER_SUCCESS = 'ADD_TEAM_MEMBER_SUCCESS';
export const ADD_TEAM_MEMBER_FAIL = 'ADD_TEAM_MEMBER_FAIL';

export const DELETE_TEAM_MEMBER_START = 'DELETE_TEAM_MEMBER_START';
export const DELETE_TEAM_MEMBER_SUCCESS = 'DELETE_TEAM_MEMBER_SUCCESS';
export const DELETE_TEAM_MEMBER_FAIL = 'DELETE_TEAM_MEMBER_FAIL';

export const GET_PROJECT_TEAMS_START = 'GET_PROJECT_TEAMS_START';
export const GET_PROJECT_TEAMS_FAIL = 'GET_PROJECT_TEAMS_FAIL';
export const GET_PROJECT_TEAMS_SUCCESS = 'GET_PROJECT_TEAMS_SUCCESS';

export const GET_TEAM_USERS_START = 'GET_TEAM_USERS_START';
export const GET_TEAM_USERS_FAIL = 'GET_TEAM_USERS_FAIL';
export const GET_TEAM_USERS_SUCCESS = 'GET_TEAM_USERS_SUCCESS';

export const SHOW_MODAL_START = 'SHOW_MODAL_START';
export const SHOW_MODAL_SUCCESS = 'SHOW_MODAL_SUCCESS';
export const HIDE_MODAL_SUCCESS = 'HIDE_MODAL_SUCCESS';
export const SHOW_MODAL_WITH_ID_PROJECT_SUCCESS = 'SHOW_MODAL_WITH_ID_PROJECT_SUCCESS';
export const SHOW_MODAL_WITH_ID_TEAM = 'SHOW_MODAL_WITH_ID_TEAM';
export const SHOW_EDIT_LEVEL_MODAL = 'SHOW_EDIT_LEVEL_MODAL';
export const SHOW_TASK_MODAL = 'SHOW_TASK_MODAL';

export const SAVE_NEW_TASK_START ='SAVE_NEW_TASK_START'
export const SAVE_NEW_TASK_FAIL ='SAVE_NEW_TASK_FAIL'
export const SAVE_NEW_TASK_SUCCESS ='SAVE_NEW_TASK_SUCCESS'

export const GET_TASKS_START = 'GET_TASKS_START'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_TASKS_FAIL = 'GET_TASKS_FAIL'

export const GET_TASK_START = 'GET_TASK_START'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const GET_TASK_FAIL = 'GET_TASK_FAIL'

export const DELETE_TASK_START = 'DELETE_TASK_START'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL'

export const EDIT_TASK_START = 'EDIT_TASK_START'
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_FAIL = 'EDIT_TASK_FAIL'

export const CLEAN_USER_STATE = 'CLEAN_USER_STATE'
export const USER_UPDATE_DATA_START = 'USER_UPDATE_DATA_START';
export const USER_UPDATE_DATA_FAIL = 'USER_UPDATE_DATA_FAIL';
export const USER_UPDATE_DATA_SUCCESS = 'USER_UPDATE_DATA_SUCCESS';

export const COLLAPSE_LATERAL_MENU_SUCCESS = 'COLLAPSE_LATERAL_MENU_SUCCESS';

export const GET_USERS_BY_PROJECT_START = 'GET_USERS_BY_PROJECT_START'
export const GET_USERS_BY_PROJECT_SUCCESS = 'GET_USERS_BY_PROJECT_SUCCESS'
export const GET_USERS_BY_PROJECT_FAIL = 'GET_USERS_BY_PROJECT_FAIL'

export const SAVE_NEW_COMMENT_START = 'SAVE_NEW_COMMENT_START'
export const SAVE_NEW_COMMENT_SUCCESS = 'SAVE_NEW_COMMENT_SUCCESS'
export const SAVE_NEW_COMMENT_FAIL = 'SAVE_NEW_COMMENT_FAIL'

export const GET_COMMENTS_START = 'GET_COMMENTS_START'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL'

export const EDIT_COMMENTS_START = 'EDIT_COMMENTS_START'
export const EDIT_COMMENTS_SUCCESS = 'EDIT_COMMENTS_SUCCESS'
export const EDIT_COMMENTS_FAIL = 'EDIT_COMMENTS_FAIL'

export const DELETE_COMMENTS_START = 'DELETE_COMMENTS_START'
export const DELETE_COMMENTS_SUCCESS = 'DELETE_COMMENTS_SUCCESS'
export const DELETE_COMMENTS_FAIL = 'DELETE_COMMENTS_FAIL'

export const APPLY_TASK_FILTERS = 'APPLY_TASK_FILTERS'
export const APPLY_TASK_SEARCH_FILTER = 'APPLY_TASK_SEARCH_FILTER'